name: Start Baking

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  label-name:
    description: The label name for issues that are baking
    default: bake-time
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/github-script@v5
    with:
      github-token: ${{ inputs.github-token }}
      script: |
        await github.rest.issues.addLabels({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          labels: ['${{ inputs.label-name }}']
        });
        const { data: checkCreation } = await github.rest.checks.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          name: 'Baking...',
          head_sha: context.payload.pull_request.head.sha,
          status: 'in_progress',
          output: {
            title: 'Waiting for the delay to pass before merging',
            summary: 'This check will pass once the delay is over'
          }
        });
        console.log(`Created check run, details: ${JSON.stringify(checkCreation, undefined, 3)}`);