name: Bake Time
description: Check pull requests have baked before they are merged

branding:
  icon: 'watch'
  color: 'green'

inputs:
  delay-hours:
    description: How many hours before pull requests have finished baking
    default: 24
    required: false
  check-name:
    description: The name of the check that is used to block baking pull requests, recommend "Baking pull request..."
    required: true

runs:
  using: 'node12'
  main: 'dist/main.js'
