name: Bake Time
description: Check pull requests have baked before they are merged

branding:
  icon: 'watch'
  color: 'green'

inputs:
  delay-hours:
    description: How many hours before pull requests have finished baking
    default: 24
    required: false
  ignore-non-push-updates:
    description: Controls if the bake timer uses the last update to the PR like approvals or the just the last push to calculate the remaining time
    default: "true"
    required: false
  check-name:
    description: The name of the check that is used to block baking pull requests, recommend "Baking pull request..."
    required: true

runs:
  using: "composite"
  steps:
  - name: "Failing check to enforce bake time"
    if: github.event_name == 'pull_request'
    shell: bash
    run: |
      echo "::error title="Baking pull request..."::This pull request will be delayed ${{ inputs.delay-hours }} hours until the bake time is over"
      exit 1

  - name: Finish baking outstanding pull requests
    if: github.event_name != 'pull_request' # For any other invocations use the finish baking workflow. e.g. workflow_dispatch or schedule
    uses: actions/github-script@v6.4.0
    with:
      script: |
        const delayHours = ${{ inputs.delay-hours }};
        const millisInAnHour = 60 * 60 * 1000;
        const delayMilliseconds = delayHours * millisInAnHour;

        // Only check pull requests with the label
        const { data: pullRequests } = await github.rest.pulls.list({
          owner: context.repo.owner,
          repo: context.repo.repo,
          state: 'open',
        });
        
        // fetch repo events only once
        pushEvents = [];
        if ('${{ inputs.ignore-non-push-updates }}' === 'true') {
            const { data: repoEvents } = await github.rest.activity.listRepoEvents({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            pushEvents = repoEvents.filter(event => event.type === 'PushEvent');
        }

        const now = new Date();
        for (const pr of pullRequests) {
          modificationTime = pr.updated_at;
          if ('${{ inputs.ignore-non-push-updates }}' === 'true') {
            const prEvents = pushEvents.filter(event => event.payload.ref === 'refs/heads/' + pr.head.ref);
            lastPushEvent = prEvents.filter(event => event.payload.head === pr.head.sha);
            if (lastPushEvent.length < 1) {
                console.log(`No push events found for PR #${pr.number}.`);
            } else {
                console.log(`Found ${lastPushEvent.length} push events for PR #${pr.number}.`)
                lastPushEvent.sort(function(a,b){return new Date(b.created_at) - new Date(a.created_at)});
                modificationTime = lastPushEvent[0].created_at;
                console.log(`Using last push event ${modificationTime} for PR #${pr.number}.`);
            }
          }
          const modificationDate = new Date(modificationTime);

          const { data: checkRuns } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: pr.head.sha
          });

          const bakeTimeCheckRuns = checkRuns.check_runs.filter(run => run.name === '${{ inputs.check-name }}');
          if (bakeTimeCheckRuns.length < 1) {
            console.log(`No check named '${{ inputs.check-name }}' for PR #${pr.number}.`);
            for (const run of checkRuns.check_runs) {
              console.log(`Found ${run.id} named ${run.name} with status ${run.status} for PR #${pr.number}.`)
            }
            continue;
          } else if (bakeTimeCheckRuns.length > 1) {
              console.log(`Found ${bakeTimeCheckRuns.length} checks named '${{ inputs.check-name }}' for PR #${pr.number}.`)
          }

          for (const bakeTimeCheckRun of bakeTimeCheckRuns) {
            if (bakeTimeCheckRun.conclusion === "success") {
              console.log(`PR #${pr.number} check ${bakeTimeCheckRun.id} has been marked as completed.`);
              continue;
            }
  
            // Check if the pull request has not been updated in the specified delay
            if (now - modificationDate >= delayMilliseconds) {
              console.log(`Marking status check ${bakeTimeCheckRun.id} as successful for PR #${pr.number}.`);
  
              const { data: checkUpdate } = await github.rest.checks.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: bakeTimeCheckRun.id,
                status: 'completed',
                conclusion: 'success',
                output: {
                  title: 'The bake time delay has passed. This PR can be merged.',
                  summary: 'The required delay is over, and the check has passed'
                }
              });
              console.log(`Check ${bakeTimeCheckRun.id} marked as successful for PR #${pr.number}.`);
              console.log(`Detailed check update message ${JSON.stringify(checkUpdate, undefined, 3)}`);
            } else {
              // Logging for pull requests that are still waiting
              const timeRemaining = (delayMilliseconds - (now - modificationDate)) / (millisInAnHour);
              console.log(`Updating pending status check ${bakeTimeCheckRun.id} for PR #${pr.number}.`);
  
              const updateMessage = `${Math.max(timeRemaining.toFixed(0),1)} hours remain.`;
              const { data: checkUpdate } = await github.rest.checks.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: bakeTimeCheckRun.id,
                status: 'in_progress', // This value cannot be modified once completed, leaving it in if GitHub's APIs support it in the future
                conclusion: 'failure',
                output: {
                  title: updateMessage,
                  summary: 'This check will pass once the delay is over.'
                }
              });
  
              console.log(`PR #${pr.number} check ${bakeTimeCheckRun.id} needs to wait for ${timeRemaining.toFixed(2)} hours before the delay is over.`);
              console.log(`Detailed check update message ${JSON.stringify(checkUpdate, undefined, 3)}`);
            }
          }
        }
